
try{
    cascxascascascas
} catch(error){
    console.log(error);
}


try{
    loqueseaxd
} catch(error){
    console.log("Lo siento, ocurrio un error de referencia");
}

try{
    console.log("Aquí no ha pasado nada");
} catch(error){
    console.log("L siento, ocurrio un error de referencia");
}


//finally se muestra pase lo que pase 
try{
    console.log("Aquí no ha pasado nada");
} catch(error){
    console.log("L siento, ocurrio un error de referencia");
} finally {
    console.log("me muestro igual");
}